name: Bro
on: 
  push: 
    branches:
      - develop
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Bro!"
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4.2.2
     - run: ls
     - run: echo "Ce workflow a été trigger sur un événement de type ${{ github.event_name }}"
     - run: echo " ${{ github.actor }} | Utilisateur ayant déclenché l’action |"
     - run: echo " ${{ github.sha }} | SHA du commit déclencheur |"
     - run: echo " ${{ github.workflow }} | Nom du workflow en cours |"
     - run: echo " ${{ runner.arch }} | Architecture CPU du runner |"
     - run: echo " ${{ env.HOME }} | Répertoire personnel dans le runner |"
  android-app-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew build
